import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '1000 Dead Ideas',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth focus:scroll-auto">
      <body className="text-pretty bg-stone-900 text-stone-100">{children}</body>
    </html>
  );
}
